version: "3"

services:
  reverse-proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - 8080:8080    

  nodejs1:
    image: docker/dockernodejs1
    container_name: nodejs1
    ports:
      - 8081:8080
  nodejs2:
    image: docker/dockernodejs2
    container_name: nodejs2
    ports:
      - 8082:8080