- name: Update apt packages
  apt:
    name: "{{ item }}"
# ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2',"lsb-release', 'software-properties-common']
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - lsb-release
    - gnupg

- name: Add Docker Gpg apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    # state: present
    # filename: docker

- name: Update apt and install docker-engine
  apt:
    name: "{{ item }}" 
# ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
